export const companies = [
  {
    handle: 'technova',
    name: 'TechNova',
    sector: 'Consumer Electronics',
    logo: '📱',
    color: '#2563EB',
    tagline: 'Smartphones & gadgets',
  },
  {
    handle: 'urbaneats',
    name: 'UrbanEats',
    sector: 'Food & Delivery',
    logo: '🍕',
    color: '#EA580C',
    tagline: 'QSR & food delivery',
  },
  {
    handle: 'skyride',
    name: 'SkyRide',
    sector: 'Ride-Hailing & Mobility',
    logo: '🚕',
    color: '#16A34A',
    tagline: 'Cab & ride services',
  },
  {
    handle: 'novapay',
    name: 'NovaPay',
    sector: 'Payments & Banking',
    logo: '💳',
    color: '#7C3AED',
    tagline: 'Digital wallets & UPI',
  },
  {
    handle: 'pacificair',
    name: 'PacificAir',
    sector: 'Airlines',
    logo: '✈️',
    color: '#0369A1',
    tagline: 'Air travel & flights',
  },
  {
    handle: 'zenwear',
    name: 'ZenWear',
    sector: 'Fashion & Apparel',
    logo: '👗',
    color: '#DB2777',
    tagline: 'Apparel & footwear',
  },
];